import { File } from '@asyncapi/generator-react-sdk';

export default function ({ asyncapi }) {

    // Temporary static //
    const serverHost = asyncapi.servers().all()[0].host();
    //const channelAddress = asyncapi.channels().all()[0].address();

    const mcpTools = asyncapi.operations().all().map(operation => {
        const operationId = operation.id();// Extract topic and operation payload
        const channelAddress = operation.channels().all()[0].address();
        const payloadSchema = operation.messages().all()[0].payload();
        const properties = payloadSchema.properties();

        const propNames = Object.keys(properties);

        const keyField = propNames.find(prop =>
            ['id', 'username', 'userid', 'email', 'name'].includes(prop.toLowerCase())
        );

        // If there is no regular KeyField, gives a default key value
        const pythonKey = keyField ? `str(${keyField})` : '"mcp_event"';

        // 1. Build function params (example: name:str, surname:str)
        const funcParams = Object.keys(properties).map(propName => `${propName}: str`).join(', ');

        // 2. Build data dictionary to send to kafka
        const dictEntries = Object.keys(properties).map(propName => `"${propName}": ${propName}`).join(',\n        ');

        // Template for each tool 
        return `
@mcp.tool
def ${operationId}(${funcParams}) -> str:
    """Sends event to topic ${channelAddress}"""
    if kafka_client is None:
        return "Error: Kafka service is not available"
    
    # AsyncAPI doc-based payload autogenerated
    user_data = {
        ${dictEntries}
    }

    try:
        kafka_client.send_event(
            topic='${channelAddress}',
            message=user_data,
            # Temporary generic key
            key=${pythonKey} 
        )
        return f"Event successfully sent to ${channelAddress}."
    except Exception as e:
        return f"Error: failed when trying to send event: {e}"
`;
    }).join('\n'); // Join each generated function

    return (
        <File name="mcp_server.py">
            {`from fastmcp import FastMCP
from kafka_producer import MyProducer

mcp = FastMCP("AsyncAPI-Kafka-Server")

try:
    kafka_client = MyProducer(['${serverHost}'])
    print("Kafka connection established")
except Exception as e:
    print(f"Error: Couldn't connect to Kafka. {e}")
    kafka_client = None
${mcpTools}

if __name__ == "__main__":
    mcp.run()
`}
        </File>
    );
}